{{- if .Values.keyring }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netwatch.fullname" . }}-keyring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netwatch.labels" . | nindent 4 }}
type: Opaque
stringData:
  keyring.yaml: |
    keyring:
    {{- range .Values.keyring }}
      - {{ . | quote }}
    {{- end }}
{{- end }}
